language: cpp
sudo: false
compiler:
  - gcc
env:
  - CC=gcc-4.8 CXX=g++-4.8 CMAKE_VARS="-D CMAKE_BUILD_TYPE=Debug -D USE_OPENMP=ON" OMP_NUM_THREADS=2
script: .travis/build.sh
addons:
  apt:
    sources:
      # Add PPAs with more up-to-date toolchains
      - ubuntu-toolchain-r-test
    packages:
      - libopencv-dev
      - libeigen3-dev
      - libgtest-dev
      - gcc-4.8
      - g++-4.8
