language: cpp
sudo: false
compiler:
  - gcc
env:
  - CMAKE_VARS="-D CMAKE_BUILD_TYPE=Debug -D USE_OPENMP=ON" OMP_NUM_THREADS=2
script: .travis/build.sh
addons:
  apt:
    packages:
      - libopencv-dev
      - libeigen3-dev
      - libgtest-dev
